import Head from 'next/head';
import { useState } from 'react';
import GridLayout from '../components/GridLayout';
import GridLayoutSettings from '../components/GridLayoutSettings';
import { IndexedObject } from '../types';
import GridItemSettings from '../components/GridItemSettings';

export default function Home() {
  const [column, setColumn] = useState<number[] | []>([]);
  const [gridCol, setGridCol] = useState('4');
  const [gridRow, setGridRow] = useState('4');
  const [gridFlow, setGridFlow] = useState('col');
  const [colStart, setColStart] = useState<IndexedObject>({});
  const [rowStart, setRowStart] = useState<IndexedObject>({});
  const [colSpan, setColSpan] = useState<IndexedObject>({});
  const [rowSpan, setRowSpan] = useState<IndexedObject>({});
  const [gap, setGap] = useState('4');

  const [settingsLayout, setSettingsLayout] = useState<number | null>(null);

  return (
    <>
      <Head>
        <title>Grid Playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full h-screen grid gap-6 grid-cols-1 grid-rows-[auto_1fr]">
        <div className="text-center mt-10">
          <h1 className="text-2xl font-bold font-mono">CSS GRID Playground</h1>
        </div>
        <div className="flex flex-col mx-6 mb-6 sm:flex-row sm:mx-20 sm:mb-20 sm:justify-between">
          <GridLayout
            column={column}
            gridCol={gridCol}
            gridRow={gridRow}
            gridFlow={gridFlow}
            colStart={colStart}
            rowStart={rowStart}
            colSpan={colSpan}
            rowSpan={rowSpan}
            gap={gap}
            setSettingsLayout={setSettingsLayout}
          />
          {settingsLayout === null ? (
            <GridLayoutSettings
              column={column}
              setColumn={setColumn}
              gridCol={gridCol}
              gridRow={gridRow}
              gridFlow={gridFlow}
              setGridCol={setGridCol}
              setGridRow={setGridRow}
              setGridFlow={setGridFlow}
              gap={gap}
              setGap={setGap}
            />
          ) : (
            <GridItemSettings
              setRowStart={setRowStart}
              setColStart={setColStart}
              setColSpan={setColSpan}
              setRowSpan={setRowSpan}
              itemIndex={settingsLayout}
              setSettingsLayout={setSettingsLayout}
            />
          )}
        </div>
      </main>
    </>
  );
}
